print("hissssss....")
print ("hola mundo")
print("mi", "nombre", "es", "monty", sep="**")
print("python.")
print("mi", "nombre", "es", "monty", sep="**", end="...\n")
print("python.")
print("        *        "*2)
print("       * *       "*2)
print("      *   *      "*2)
print("     *     *     "*2)
print("    *       *    "*2)
print("   *         *   "*2)
print("  *           *  "*2)
print(" *             * "*2)
print("*****       *****"*2)
print("    *       *    "*2)
print("    *       *    "*2)
print("    *       *    "*2)
print("    *       *    "*2)
print("    *       *    "*2)
print("    *********    "*2)
print("Mi\nnombre\nes\nBond.", end=" ")
print("James Bond.")
print(0x123)

